openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22027
servers:
  - url: https://library.com
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/pathPagination'

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    put:
       tags:
         - Books
       summary: Create or update a list of books
       operationId: crupdateBooks
       requestBody:
        content:
         application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Book"

       responses:
         200:
           description: Success
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SuccessResponse'

         400:
           description: Bad request
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ClientErrorResponse'

         403:
           description: Forbidden
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ClientErrorResponse'

         500:
           description: Server error
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ServerErrorResponse'
  /authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - Authors

      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/pathPagination'

        - name: authorName
          in: query
          description: Filter returned authors by given name.
          schema:
            type: string
          required: false

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    put:
      summary: Create or update authors
      operationId: crupdateAuthors
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    delete:
      tags:
        - Authors
      summary: Delete author by id
      description: Deleting an author by id
      parameters:
        - name: authorName
          in: query
          required: true
          schema:
            type: string
      responses:
          "200":
            description: Author deleted successfully

components:

  parameters:
    queryPagination:
      name: page
      in: query
      schema:
        type: object
        properties:
          page:
            type: integer
            default: 1

    pathPagination:
      name: pageSize
      in: path
      schema:
        type: object
        properties:
          pageSize:
            type: integer
      required: true

  schemas:

    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    Author:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F

    Response:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: string
              default: "Default code"
            message:
              type: string
              default: "default message"
        body:
          type: object

    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            status:
              properties:
                code:
                  type: string
                  default: "200"
                message:
                  type: string
                  default: "Success request"
            body:
              type: object
              properties:
                successData:
                  type: string
                  default: "Default success data"


    ClientErrorResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            status:
              properties:
                code:
                  type: string
                  default: "400"
                message:
                  type: string
                  default: "Bad request"
            body:
              type: object
              properties:
                clientErrorData:
                  type: string
                  default: "Default client error data"

    ServerErrorResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            status:
              properties:
                code:
                  type: string
                  default: "500"
                message:
                  type: string
                  default: "Internal Server Error"
            body:
              type: object
              properties:
                serverErrorData:
                  type: string
                  default: "An internal server error has occurred. Please try again later."


    ImportAuthorJSON:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string

    ImportAuthorExcel:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
