openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: STD22027
servers:
  - url: https://library.com
tags:
  - Books
  - Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string

        - in: query
          name: releaseDateFrom
          description: Filter books released on after the date.
          required: false
          schema:
            type: string
            format: date
        - in : query
          name: releaseDateTo
          description: Filter books released on before the date.
          required: false
          schema:
            type: string
            format: date

      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /authors:
    get:
      tags:
        - Authors
      summary: get all authors
      description: filter a list of all authors by name
      operationId: getAuthor
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name.
          required: false
          schema:
            type: string

      responses:
        200:
          description: the list of author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Authors'

    put:
      tags:
        - Authors
      summary: create or update an author
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
               $ref: '#/components/schemas/Authors'

      responses:
        200:
          description: the list of create or update authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Authors'

    delete:
      tags:
        - Authors
      summary: Delete an authors
      description: delete an author by their Id.
      operationId: deleteAuthor
      parameters:
        - in: query
          name: authorId
          description: the ID of the author to delete.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful request

  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      summary: Update the Author of a Book
      operationId: UpdateTheAuthorOfaBook
      parameters:

        - name: bookId
          in: path
          required: true
          schema:
            type: string
          description: ID of the Book

        - name: authorId
          in: path
          required: true
          schema:
            type: string
          description: ID of the Author

      responses:
        '200':
          description: the update book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/authors:
    put:
      tags:
        - Books
      summary: Create an association between a Book and an Author
      description: List of associations to create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookAuthor'

      responses:
        '200':
          description: Successful association creation

components:
  schemas:
    Book:
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
      type: object
      properties:
        author:
          $ref: '#/components/schemas/Authors'

    Authors:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          type: string
          enum:
            - M
            - F

    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string

# Reponses sur le TD2

#2-b-i) UpdateBookAuthor ne contient que les identifiants pour modifier l'association entre un Book et un Author,
  #sans inclure les autres propriétés telles que bookName et authorName, car son but principal est de gérer cette association
  #sans affecter les détails spécifiques de ces entités.

#2-b-ii) UpdateBookAuthor devrait inclure les propriétés de CrupdateBook et Author lorsqu'une mise à jour de l'association
  #entre un Book et un Author doit également permettre la modification des détails spécifiques de ces entités en même temps.

#3-a) La pagination est nécessaire pour faciliter la gestion des grands quantités de données.

#4-a) Oui, il est possible de gérer la pagination à travers les en-tête de la requête mais cette approche n'est pas recommandée
  # car elle ne suit pas les conventions,ce qui peut compliquer la compréhension et la gestion de la pagination pour les développeurs.
#4-b) Non, en général, il n'est pas recommandé de gérer la pagination à travers les en-têtes  car il ne suit pas les conventions courantes de conception
